### ISSUE TITLE
Remove pyenv duplicate command and add no-rehash

### ISSUE THREAD

**Issue by eugenesvk** [dyuri/xontrib-langenv#10]
While checking why pyenv init is so slow, I've realized that your xontrib runs it twice for no reason since the full init already provides PATH

```xsh
PYENV_PATH = $(@(PYENV) init --path)  # this is not needed since ↓ already includes `export PATH`
PYENV_ENV = $(@(PYENV) init -)
```

Also there is another trick to speed it up via `pyenv init - --no-rehash` instead of the regular `init`
https://github.com/pyenv/pyenv/discussions/1970

**Comment by dyuri** [comment]
Thanks, 1.0.8 released including these changes.
