### ISSUE TITLE
Want to expand to do nodenv/goenv/rbenv as well?

### ISSUE THREAD

**Issue by drmikecrowe** [dyuri/xontrib-langenv#5]
I forked and now have [nodenv](https://github.com/nodenv/nodenv) and [goenv](https://github.com/syndbg/goenv) working (tackling `rbenv` now).

Would you like to rename yours and included these in a generic `pygonerb` env repo?

I could do the others as separate pip packages, but I'd prefer to collaborate with you.

Here's [my changes](https://github.com/dyuri/xontrib-pyenv/compare/master...drmikecrowe:master)

**Comment by dyuri** [comment]
Sure, but I think we'd need a better name, without the need to rename it on every new supported language :)

**Comment by dyuri** [comment]
What's your opinion about `xontrib-langenv`? I don't think that it's possible to rename the project on PyPI, but we can create a new one, and deprecate this one (add a note to github/pypi, remove the code and add the new project as dependency, or something like that).

**Comment by drmikecrowe** [comment]
I like it a lot. Let me submit a PR with my changes for you

**Comment by dyuri** [comment]
Thanks, I'll take a look tomorrow and try to handle the "renaming".

**Comment by dyuri** [comment]
Renamed & new package released on PyPI.
Going to create placeholder `xontrib-pyenv` later.
