### ISSUE TITLE
With Ubuntu 22.04 I can't use this if I load pyenv

### ISSUE THREAD

**Issue by jd-0001** [dyuri/xontrib-langenv#8]
I tried installing this in my latest ubuntu 22.04 and I added it in `.xonshrc` file.

Now if I open the terminal it immediately closes within a blink of an eye.

However, I managed to get the output:
![image](https://user-images.githubusercontent.com/47495003/164557397-57d76d5b-4269-48b2-ad64-42c0ab32a530.png)

_(Actually in order to make it work I added `source-bash ~/.bashrc` & `.profile` on top of the .xonshrc) but without them I was getting source-foreign error_

**Comment by dyuri** [comment]
What's the version of `xonsh` you are using? That change with `-n` was introduced for `xonsh v12`, if you are using earlier xonsh, you might use `1.0.6` (if that works I'll update the readme).

**Comment by jd-0001** [comment]
I was using apt-get to install xonsh. Now I am using pip and the error doesn't seem to appear.

Closing this.

**Comment by dyuri** [comment]
I'll add a note to the readme though.
